{
 "title": "UC - USA",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CUBE 01 - Gigabit 1 - LAN",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ifDescr $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 1s) *8 AS \"Input\" FROM \"interface\" WHERE (\"hostname\" = 'CSR-1000v01.aus.presidio.local' AND \"ifDescr\" = 'GigabitEthernet1') AND $timeFilter GROUP BY time($__interval), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Input" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "CSR-1000v01.aus.presidio.local" },
      { "condition": "AND", "key": "ifDescr", "operator": "=", "value": "GigabitEthernet1" }
     ]
    },
    {
     "alias": "$tag_ifDescr $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT derivative(mean(\"ifHCOutOctets\"), 1s) *8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'CSR-1000v01.aus.presidio.local' AND \"ifDescr\" = 'GigabitEthernet1') AND $timeFilter GROUP BY time($__interval), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Output" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "CSR-1000v01.aus.presidio.local" },
      { "condition": "AND", "key": "ifDescr", "operator": "=", "value": "GigabitEthernet1" }
     ]
    }
   ]
  },
  {
   "title": "CUBE 01 - Gigabit 2 - ISP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ifDescr $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 1s) *8 AS \"Input\" FROM \"interface\" WHERE (\"hostname\" = 'CSR_1000v02.aus.presidio.local' AND \"ifDescr\" = 'GigabitEthernet1') AND $timeFilter GROUP BY time($__interval), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Input" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "CSR-1000v01.aus.presidio.local" },
      { "condition": "AND", "key": "ifDescr", "operator": "=", "value": "GigabitEthernet2" }
     ]
    },
    {
     "alias": "$tag_ifDescr $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT derivative(mean(\"ifHCOutOctets\"), 1s) *8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'CSR-1000v02.aus.presidio.local' AND \"ifDescr\" = 'GigabitEthernet1') AND $timeFilter GROUP BY time($__interval), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Output" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "CSR-1000v01.aus.presidio.local" },
      { "condition": "AND", "key": "ifDescr", "operator": "=", "value": "GigabitEthernet2" }
     ]
    }
   ]
  },
  {
   "title": "USA - CUBE 01 - RTP Connection",
   "type": "graph",
   "description": "Number of RTP Connection on CUBE 01",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "RTP_Connection",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "USA_cube01" }
     ]
    }
   ]
  },
  {
   "title": "USA - CUBE 02 - RTP Connection",
   "type": "graph",
   "description": "Number of RTP Connection on CUBE 02",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "RTP_Connection",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "USA_cube02" }
     ]
    }
   ]
  }
 ]
}